### PR TITLE
Feature/bertqakotlin

### LINKED ISSUE #2: Bert Qa Kotlin sample
- Understanding [TFLite Bert Qa sample app](https://github.com/SunitRoy2703/examples/tree/1273c41c66ff38cec3023f7383f74db34f8b8eaa/lite/examples/bert_qa/android) in JAVA
- Rewriting TFLite Bert Qa sample app in Kotlin with only Task Library Implementation 
-  Rewriting tests in kotlin is not mandatory but is recommended 

TFLite Bert Qa sample app in java for reference: https://github.com/SunitRoy2703/examples/tree/1273c41c66ff38cec3023f7383f74db34f8b8eaa/lite/examples/bert_qa/android

### PR DESCRIPTION
**Pull request by dhruvnagarajan**
Closes #2 

ss

### CODE REVIEW

**Comment by SunitRoy2703** [comment]
@dhruvnagarajan 
Give me some time,  I'll review it properly

**Comment by SunitRoy2703** [comment]
@dhruvnagarajan
 Great work! App is working fine,
 but the tests are in java and have some errors

Anyways I'm merging it!
I'll create a separate issue for the tests and if you want you can work on it

**Comment by dhruvnagarajan** [comment]
Yeah will update tests

**Comment by SunitRoy2703** [comment]
> Yeah will update tests

I have created issue #13 for this, you can take it

**Pull request merged**
